/**
 * 
 */
$(document).ready(function(){
	$("#easeInElastic").click(function(){
	//	alert('aa')
		$('div').animate({
			left:500
		},2000,'easeInElastic')
	})
	$("#easeOutElastic").click(function(){
		//alert('bb')
		$('div').animate({
			left:0
		},2000,'easeOutElastic')
	})
	$("#a").click(function(){
		$("div").animate({width:2},'fast')
	})
})